
insert into user_entity (account_non_expired, account_non_locked, avatar,credentials_non_expired, enabled, first_name, last_name, password, phone,  email, roles, username, id) values (true, true, 'https://robohash.org/ale',true, true, 'Alejandro', 'Fernandez', '{bcrypt}$2a$12$H3ll7X8X096PtEsIBEIcxOTGksMp6T6wib6mTOi31v9CH/NI/Rp2a', '618123995','alejantus06@gmail.com','USER', 'ale1234', 'd55285a1-154f-4956-8498-cad29c58fb4d')
insert into user_entity (account_non_expired, account_non_locked, avatar,credentials_non_expired, enabled, first_name, last_name, password, phone, email,roles, username, id) values (true, true, 'https://robohash.org/luismi',true, true, 'Luis Miguel', 'Lopez', '{bcrypt}$2a$12$H3ll7X8X096PtEsIBEIcxOTGksMp6T6wib6mTOi31v9CH/NI/Rp2a', '619971902','admin@gmail.com','ADMIN', 'admin', 'b6511083-930a-4a0e-882d-e536af7cb35c')

insert into league (id, league_name) values (NEXTVAL('hibernate_sequence'),'KingsLeague')
insert into league (id, league_name) values (NEXTVAL('hibernate_sequence'),'La Liga Santander')

insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Porcinos FC', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Ultimate Mostoles', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Saiyans FC', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'ElBarrio', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'PIO', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), '1K', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Kunisports', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Troncos FC', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Jijantes FC', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Aniquiladores FC', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Xbuyer Team', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Rayo de Barcelona', 1)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Real Betis Balompie', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Sevilla FC', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Real Madrid', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'FC Barcelona', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Atletico de Madrid', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Real Valladolid', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Real Sociedad', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Villarreal', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Valencia', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Athletic Club', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Elche', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Girona', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Osasuna', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Rayo Vallecano', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Getafe', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Cadiz', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Almería', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Celta de Vigo', 2)
insert into team (id, team_name, league_id) values (NEXTVAL('hibernate_sequence'), 'Espanyol', 2)

insert into post (id , date , image , title , user_id) values (NEXTVAL('hibernate_sequence'),current_timestamp,'logoWindows.png','El mejor dia de mi vida','d55285a1-154f-4956-8498-cad29c58fb4d')
insert into post (id , date , image , title , user_id) values (NEXTVAL('hibernate_sequence'),current_timestamp,'logoWindows.png','El peor dia de mi vida','d55285a1-154f-4956-8498-cad29c58fb4d')

insert into comment (id, content, date , post_id , user_id) values (NEXTVAL('hibernate_sequence'),'No es muy entretenida',current_timestamp , 34,'d55285a1-154f-4956-8498-cad29c58fb4d')
insert into comment (id, content, date , post_id , user_id) values (NEXTVAL('hibernate_sequence'), 'Es muy entretenida',current_timestamp , 34,'d55285a1-154f-4956-8498-cad29c58fb4d')
insert into comment (id, content, date , post_id , user_id) values (NEXTVAL('hibernate_sequence'), 'No comprendo tu foto',current_timestamp , 34,'d55285a1-154f-4956-8498-cad29c58fb4d')
insert into comment (id, content, date , post_id , user_id) values (NEXTVAL('hibernate_sequence'), 'Es muy divertida',current_timestamp , 34,'d55285a1-154f-4956-8498-cad29c58fb4d')
insert into comment (id, content, date , post_id , user_id) values (NEXTVAL('hibernate_sequence'), 'No entendi la referencia',current_timestamp , 35,'d55285a1-154f-4956-8498-cad29c58fb4d')
insert into comment (id, content, date , post_id , user_id) values (NEXTVAL('hibernate_sequence'), 'Divertidisimo',current_timestamp , 35,'d55285a1-154f-4956-8498-cad29c58fb4d')
insert into comment (id, content, date , post_id , user_id) values (NEXTVAL('hibernate_sequence'), 'No me gusta nada tu foto',current_timestamp , 35,'d55285a1-154f-4956-8498-cad29c58fb4d')
insert into comment (id, content, date , post_id , user_id) values (NEXTVAL('hibernate_sequence'), 'Es muy entretenida',current_timestamp , 35,'d55285a1-154f-4956-8498-cad29c58fb4d')

insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'33','España' , 176, 10, 'Sergio Canales','Centrocampista',65,3)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'37','España' , 184, 4, 'Sergio Ramos','Defensa',65,4)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'30','España' , 187, 9, 'Borja Iglesias','Delantero',65,5)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'40','Chile' , 184, 1, 'Claudio Bravo','Portero',65,6)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'29','Francia' , 173, 8, 'Nabil Fekir','Centrocampista',72,7)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'26','Brasil' , 187, 19, 'Luiz Felipe','Defensa',65,8)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'38','Portugues' , 176, 7, 'Cristiano Ronaldo','Delantero',65,9)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'30','Brasil' , 193, 10, 'Alisson','Portero',91,10)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'30','España' , 169, 7, 'Juanmi','Centrocampista',65,11)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'31','Argentina' , 190, 6, 'German Pezzella','Defensa',82,12)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'35','Argentina' , 170, 10, 'Messi','Delantero',65,13)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'32','España' , 192, 1, 'David De Gea','Portero',82,14)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'33','Alemania' , 183, 8, 'Toni Kroos','Centrocampista',65,15)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'30','Senegal' , 174, 23, 'Sabaly','Defensa',66,16)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'32','Francia' , 176, 8, 'Antoine Griezmann','Delantero',65,17)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'29','Portugues' , 189, 13, 'Rui Silva','Portero',85,18)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'37','Croacia' , 172, 10, 'Luka Modric','Centrocampista',65,19)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'31','Países Bajos' , 195, 10, 'Virgil van Dijk','Defensa',92,20)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'36','Uruguay' , 182, 9, 'Luis Suárez','Delantero',65,21)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'37','Alemania' , 193, 1, 'Manuel Neuer','Portero',65,22)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'41','España' , 179, 17, 'Joaquin Sánchez','Centrocampista',65,23)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'36','España' , 194, 3, 'Gerard Pique','Defensa',65,24)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'35','Francia' , 185, 19, 'Karim Benzema','Delantero',65,25)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'31','Alemania' , 187, 1, 'Ter Stegen','Portero',65,26)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'33','Alemania' , 185, 25, 'Thomas Müller','Centrocampista',65,27)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'32','España' , 184, 3, 'Marc Bartra','Defensa',65,28)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'41','España' , 169, 24, 'Rubén Castro','Delantero',65,29)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'31','Bélgica' , 200, 1, 'Courtois','Portero',96,30)
insert into player (id , age , country , height , jersey_number , name , position , weight , team_id) values (NEXTVAL('hibernate_sequence'),'19','Inglaterra' , 186, 22, 'Jude Bellingham','Centrocampista',65,31)
